applications:
    app:
        type: golang:1.22
        # stack:
        #   - "golang@1.22"
        hooks:
            build: |
                go build -o bin/app
        relationships:
            database:
        web:
            upstream:
                socket_family: tcp
                protocol: http
            commands:
                start: ./bin/app
            locations:
                /:
                    allow: false
                    passthru: true

services:
    database:
        type: mariadb:11.2
