applications:
    app:
        type: golang:1.22
        hooks:
            build: |
                go build -o bin/app
        relationships:
            database:
        web:
            upstream:
                socket_family: tcp
                protocol: http
            commands:
                start: ./bin/app
            locations:
                /:
                    allow: false
                    passthru: true

services:
    database:
        type: mariadb:11.2

# routes:
#     "https://{default}/":
#         type: upstream
#         upstream: "app:http"

#     "https://www.{default}/":
#         type: redirect
#         to: "https://{default}/"