# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
app:
    # The runtime the application uses.
    type: golang:1.22
    # The hooks executed at various points in the lifecycle of the application.
    hooks:
        build: |
            # Modify this line if you want to build differently or use an alternate name for your executable.
            go build -o bin/app
    # The relationships of the application with services or other applications.
    #
    # The left-hand side is the name of the relationship as it will be exposed
    # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
    # side is in the form `<service name>:<endpoint name>`.
    relationships:
        database: "db:mysql"
    # The configuration of app when it is exposed to the web.
    web:
        upstream:
            socket_family: tcp
            protocol: http
        commands:
            # If you change the build output in the build hook above, update this line as well.
            start: |
                export DATABASE_USERNAME=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0].username')
                export DATABASE_PASSWORD=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0].password')
                export DATABASE_HOST=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0].host')
                export DATABASE_PORT=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0].port')
                export DATABASE_PATH=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0].path')
                ./bin/app
        locations:
            /:
                # Route all requests to the Go app, unconditionally.
                # If you want some files served directly by the web server without hitting Go, see
                # https://docs.platform.sh/configuration/app/web.html
                allow: false
                passthru: true
    # The size of the persistent disk of the application (in MB).
    disk: 1024
